version: "3.9"
services:
  python-api:
    build: microservices\python\.
    container_name: python-api
    hostname: python-api
    ports:
      - "5551:5551"

  javascript-api:
    build: microservices\javascript\.
    container_name: javascript-api
    hostname: javascript-api
    ports:
      - "5552:5552"

  csharp-api:
    build: microservices\csharp\.
    container_name: csharp-api
    hostname: csharp-api
    ports:
      - "5553:5553"

  rust-api:
    build: microservices\rust\.
    container_name: rust-api
    hostname: rust-api
    ports:
      - "5554:5554"
